---
title: "Credit Clearing Capability"
format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
---

The value S used to determine the maximum number of courses that the learner is permitted to register in a term is calculated as shown below.

-   Term 1: decided by qualifier marks\
-   Term 2: decided by average of marks of all courses taken in Term 1 in which the learner has passed\
-   Term n (n\>2): M = average marks of courses passed in the previous two terms Term n-1 and Term n-2 (This will be calculated using marks of subjects in which the candidate has passed, not those which he/she has not passed or is not completed yet); (n-1 and n-2 terms must be terms where the learner status is Active - defined in section [11. Learner Life Cycle](#heading=h.f1n87ris0g8p)

| Marks M (as defined above) | Maximum number of courses that learner is permitted to register in any term |
|:-----------------------------------:|:-----------------------------------:|
| 0 \<= M\< 50 | 2 |
| 50 \<= M\< 70 | 3 |
| M \>= 70 | 4 |
: Table 6.1 {.striped .hover}

The credit clearing capability CCC will be decided as follows:

-   If a learner has passed at least one course in term n-1, then the CCC of term n will be calculated based on the marks as given in the above table.\
-   If a learner has failed all courses the learner has appeared for in term n-1, CCC of next term n will be 2.\
-   If a learner is absent for final exam of all courses, thus not completing their courses and not getting grades, CCC of next term = CCC of the learner’s last term

CCC is kept as 4 by default for

-   everyone who chooses to register to courses in the same term as the qualifier exam\

-   For all JEE candidates in the first term\

-   For everyone in the Diploma and Degree levels

## TODO

- [ ] Todo 1