project:
  type: book

book:
  title: "student_handbook"
  author: "Norah Jones"
  date: "4/15/2025"
  chapters:
    - index.qmd
    - references.qmd
    - 01-data-science-applications.qmd
    - fexibility.qmd
    - courses-in-the-program.qmd
    - fees-entire-program.qmd
    - 13-learning-paths-available.qmd
    - summary.qmd
    - intro.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt


navbar:
  right:
    - text: "📄 Download PDF"
      href: downloads/index.pdf
      icon: download
