project:
  type: book
  output-dir: _book
  preview:
    port: 4444
execute:
  freeze: auto

  

book:
  title: "IITM Student Handbook"
  reader-mode: true
  author: "Srinivas Chilukuri"
  date: "4/15/2025"
  page-footer:
    left: |
      Revision Date 14 April 2025.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://iitmbsc-student-projects.github.io/iitm_student_handbook_quarto/
  repo-url: https://github.com/shriaviator/iitm_student_handbook_quarto
  repo-branch: main
  repo-actions: [edit, issue,source]
  downloads: [pdf]
  chapters:
    - index.qmd
    - references.qmd
    - notice.qmd
    - 01-data-science-applications.qmd
    - 02-fexibility.qmd
    - 03-courses-in-the-program.qmd
    - 04-fees-entire-program.qmd
    - 11_design_certificates_levels_program.qmd
    - 13-learning-paths-available.qmd
    - 17-pgd-mtech-upgrade-path.qmd
    - 18-apprenticeship-in-the-bs-level.qmd
    - 19-software-hardware-requirements.qmd
    - 20-non-academic-rules.qmd
    - part: "Appendices"
      chapters:
        - dummy.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      
    page-footer:
      left: "© 2025 Your Name or Organization"
      right: "[GitHub](https://github.com/yourrepo)"
    other-links:
      - text: Disussion Forum
        icon: chat-square-dots-fill
        href: https://discourse.onlinedegree.iitm.ac.in/c/general/75
  pdf:
    documentclass: scrreprt
