name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
      # Add any additional steps as needed, such as installing dependencies
      - name: Build and Deploy
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages